name: Workflow
  
on:
  workflow_dispatch:
jobs:
  runworkflow:
    runs-on: $ {{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        version: [9.0, 8.0]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .Net
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ matrix.version }}

      - name: Build Solution
        run: dotnet build ShoppingList.sln

      - name: Print matrix values
        run: |
          echo "Running on OS: ${{ matrix.os }}"
          echo "Using .NET version: ${{ matrix.version }}"
          
      - name: TestBuildSuccess
        if: success()
        run: echo "Build successful" 
  
